### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Beyley** [swedishborgie/kinect2pipe#1]
Whenever i try to build i get 
```
-- Checking for module 'freenect2'
--   No package 'freenect2' found
``` 
i dont exactly know how to solve it as im not really a c dev

EDIT: After trying for awhile i still cant get it to import the library

**Comment by swedishborgie** [comment]
Hi @Beyley,

That error means you're missing the freenect2 library or it's not on your pkgconfig path. You can find instructions for cloning and building libfreenect2 [here](https://github.com/OpenKinect/libfreenect2/blob/master/README.md#linux).

If you're using Ubuntu, there's also a [PPA available](https://launchpad.net/~swedishborgie/+archive/ubuntu/kinect2pipe) which comes with libfreenect2.

**Comment by Beyley** [comment]
i already have libfreenect2 built and working perfectly, followed all the instructions, i saw a pkgconfig folder but 10mins of googling and i still dont understand what that means, and the PPA is focal only, and i run groovy

EDIT: after a while googling i tried to add `/home/beyley/freenect2/lib/pkgconfig/` to my $PKG_CONFIG_PATH but that didnt seem to fix anything

EDIT 2: turns out i was just exporting the variable wrong and now it gets past cmake, but when trying to run make it crashes during the build

```
[100%] Linking CXX executable kinect2pipe
/usr/bin/ld: cannot find -lfreenect2
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kinect2pipe.dir/build.make:99: kinect2pipe] Error 1
make[2]: Leaving directory '/home/beyley/kinect2pipe/build'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/kinect2pipe.dir/all] Error 2
make[1]: Leaving directory '/home/beyley/kinect2pipe/build'
```

**Comment by swedishborgie** [comment]
From the error message you're getting, it seems like you have built libfreenect2, but haven't actually installed it. The build procedure for libfreenect2 should look like this (from your /home/beyley/freenect2/ folder):

    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/freenect2
    make
    make install

The last line is the important bit. The pkgconfig files in lib/pkgconfig have paths hard coded inside of them assuming that you've installed the package. Alternatively you could adjust the pkgconfig file in that path to point to the non-installed location of `libfreenect2.so`.

For example, I built from $HOME/Projects/libfreenect2, and the lib/pkgconfig/freenect2.pc contains the following:

    prefix=/home/<USERNAME>/Projects/libfreenect2
    exec_prefix=/home/<USERNAME>/Projects/libfreenect2
    libdir=${prefix}/lib
    includedir=${prefix}/include
    
    Name: freenect2
    Description: Driver for the Kinect v2 (aka K4W)
    Version: 0.2.0
    Libs: -L${libdir} -lfreenect2
    Cflags: -I${includedir}

This tells the compiler that it can find libfreenect2.so in /home/<USERNAME>/Projects/libfreenect2/lib (prefix + libdir). The error you're getting indicates that wherever your freenect2.pc is pointing to doesn't contain that file and it's expecting it.

**Comment by Beyley** [comment]
I cloned libfreenect2 to ~/libfreenect2 i did the whole build and already had done `make install` which is what had made that ~/freenect2/ folder in the first place and populated it, although just to make sure i recloned libfreenect2, i run make then make install, it moved the files to ~/freenect2/ then i went into kinect2pipe, ran cmake, and the same error occurred

I checked the .pc file and the paths were correct

**Comment by swedishborgie** [comment]
I think I figured out what you were running into. Can you pull the latest change and try again?

The CMakeLists.txt file wasn't properly pulling the library paths from pkgconfig. It should be fixed now.

**Comment by Beyley** [comment]
I can make and make install but when trying to run it complains about 
`kinect2pipe: error while loading shared libraries: libfreenect2.so.0.2: cannot open shared object file: No such file or directory`

**Comment by swedishborgie** [comment]
Cool! You just need to copy libfreenect2.so.so.0.2 into either the same directory as kinect2pipe, or install it into a global location like /usr/lib.

**Comment by Beyley** [comment]
It works now! thanks
